name: Build and Upload Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (linux/amd64)
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag music-assistant-nosooqua:x86 \
            --output type=docker,dest=ma-x86.tar

      - name: Compress image
        run: gzip -9 ma-x86.tar

      - name: Upload image to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ma-x86.tar.gz
